### ISSUE TITLE
Add feature - use `threads` for communicate with many `Client`s

### ISSUE THREAD

**Issue by issamansur** [issamansur/ChatOnBaseSocket#5]
Needed change:
- [x] Change count of availible `Client`s from `1` to `5` (for example) 
- [x] Add `thread`s to `Server`
- [x] Add `thread`s to `Client`
- [x] Test functional on quality

**Comment by jobs-code** [comment]
can i work on this?

**Comment by issamansur** [comment]
@jobs-code Hi, yeah. But please don't do it if you don't understand/plan to use GPT/Copilot. Thank u

**Comment by issamansur** [comment]
And please check last update

**Comment by issamansur** [comment]
Now we have:
- Change count of availible `Client`s from `1` to `10`
- Add `thread`s to `Server`
- Refactor code

**Comment by issamansur** [comment]
Last commit add some functionalities:
- add `thread`s to `Client`;
- add command `/exit` to disconnect;
- add IO dif thread support;

Tested: yes
